import {VoiceControls} from './VoiceControls'
import {ModifierDragController} from '../pet/ModifierDragController'
import {useEffect,useRef,useState} from 'react'
import type {LocalChatApi,LocalChatAction,LocalChatSnapshot} from '../../electron/shared/character-chat-contract'
declare global{interface Window{characterChat:LocalChatApi}}
export function CharacterChatApp(){const [state,setState]=useState<LocalChatSnapshot|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[menu,setMenu]=useState(false);const menuButton=useRef<HTMLButtonElement>(null),bottom=useRef<HTMLDivElement>(null),header=useRef<HTMLElement>(null),resize=useRef<HTMLButtonElement>(null);
 const act=async(a:LocalChatAction)=>{try{const next=await window.characterChat.action(a);setState(old=>old&&next.epoch<old.epoch?old:next)}catch(e){setError(String(e))}};
 useEffect(()=>{const controllers:ModifierDragController[]=[];for(const [element,kind] of [[header.current,'move'],[resize.current,'resize']] as const){if(element)controllers.push(new ModifierDragController(element,{platform:'native',allowed:()=>true,hit:()=>true,request:r=>window.characterChat.gesture(kind,r),lock:active=>element.classList.toggle('dragging',active),gesture:e=>e.button===0&&!(kind==='move'&&(e.target as Element).closest('button'))}))}return()=>controllers.forEach(c=>c.dispose())},[]);
 useEffect(()=>{const off=window.characterChat.subscribe(next=>setState(old=>old&&next.epoch<old.epoch?old:next));void act({type:'snapshot'});return off},[]);
 useEffect(()=>{const list=bottom.current?.parentElement;if(list)list.scrollTop=state?.conversation?.messages.length?list.scrollHeight:0},[state?.conversation?.id,state?.conversation?.messages.at(-1)?.text]);
 const busy=state?['loading','generating','replying'].includes(state.phase):false,installed=state?.installed.includes(state.model);const send=()=>{if(!text.trim()||busy)return;const value=text;setText('');void act({type:'send',text:value})};
 return <main className="chat-bubble" onKeyDown={e=>{if(e.key==='Escape'&&menu){setMenu(false);menuButton.current?.focus()}}} onPointerDown={e=>{if(menu&&!(e.target as Element).closest('.bubble-menu, [aria-label="대화 메뉴"]'))setMenu(false)}}><header ref={header} title="끌어서 말풍선 이동"><div className="drag-space"><span className="chat-name">{state?.displayName||state?.character?.name}</span></div><button ref={menuButton} aria-label="대화 메뉴" aria-controls="chat-quick-switch" aria-expanded={menu} onClick={()=>setMenu(!menu)}>···</button><button aria-label="말풍선 닫기" onClick={()=>void act({type:'codex-mode'})}>×</button></header><VoiceControls showStatus={!menu}/>{menu&&<ChatQuickSwitch state={state} act={act} close={()=>setMenu(false)}/>}<div className="messages" aria-live="polite">{state&&!installed&&<div className="setup"><button onClick={()=>void act({type:'open-settings'})}>설정에서 모델 준비하기</button></div>}{state?.conversation?.messages.map(m=><article className={'message '+m.role} key={m.id} aria-label={m.role==='user'?'보낸 메시지':'받은 메시지'}><p>{m.text||(m.status==='streaming'?<span className="typing" role="status" aria-label="답변 준비 중"><i/><i/><i/></span>:'…')}</p>{m.role==='assistant'&&m.status==='complete'&&<button aria-label="이 답변 다시 읽기" onClick={()=>void window.characterVoice.action({type:'read',messageId:m.id})}>다시 읽기</button>}{m.status==='stopped'&&<small>중단됨</small>}{m.status==='error'&&<small>응답을 받지 못했어요</small>}</article>)}<div ref={bottom}/></div>{(state?.error||error)&&<div className="error" role="alert">{state?.error||error}</div>}<div className="composer"><textarea aria-label="메시지" onFocus={()=>void act({type:"attention",active:true})} onBlur={()=>void act({type:"attention",active:false})} placeholder="메시지" value={text} maxLength={6000} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/>{busy?<button className="send-button" aria-label="응답 중단" title="중단" onClick={()=>void act({type:'stop'})}><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="2" fill="currentColor"/></svg></button>:<button className="send-button" aria-label="보내기" title="보내기" disabled={!installed||!text.trim()} onClick={send}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 19V5m-6 6 6-6 6 6" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"/></svg></button>}</div><div className="tail"/><button ref={resize} className="resize-handle" aria-label="끌어서 말풍선 크기 조절" title="끌어서 크기 조절"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="m5 12 7-7m-2 7 2-2" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg></button></main>
}

export function ChatQuickSwitch({state,act,close}:{state:LocalChatSnapshot|null;act:(value:LocalChatAction)=>unknown;close:()=>void}){return <section id="chat-quick-switch" className="bubble-menu" aria-label="대화 선택"><label>캐릭터<select aria-label="캐릭터" value={state?.character?.id||''} onChange={e=>void act({type:'character',id:e.target.value})}>{state?.characters.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>저장된 대화<select aria-label="저장된 대화" value={state?.conversation?.id||''} onChange={e=>{void act({type:'conversation',id:e.target.value});close()}}><option value="" disabled>대화 선택</option>{state?.conversations.filter(c=>c.characterId===state.character?.id).map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label></section>}
