import {afterEach,describe,expect,it,vi} from 'vitest'
import {mkdtemp,readFile,rm,stat} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {OwnedTunnelCleanupError} from '../electron/main/dot/OwnedTunnelCleanupError'
import {BelleConnectionManager,connectionError,type RuntimeCredentialStore,type TunnelRuntime} from '../electron/main/dot/BelleConnectionManager'
import {BelleConnectionMetadata} from '../electron/main/dot/BelleConnectionMetadata'
import {BelleCredentialStore} from '../electron/main/dot/BelleCredentialStore'
import {clientVersion,nodeVersion,tunnelBaseEnv} from '../electron/main/dot/BelleTunnelRuntime'
import {connectionIds,restoredConnectionConfig,validRuntimeKey,type BelleConnectionConfig} from '../electron/shared/belle-connection'
const ids={tunnelId:'tunnel_'+'a'.repeat(32),organizationId:'org-example123'},key='sk-'+Array.from({length:24},()=> 'z').join(''),config:BelleConnectionConfig={...ids,consentVersion:1,autoConnect:false}
const managers:BelleConnectionManager[]=[],dirs:string[]=[]
afterEach(async()=>{for(const m of managers.splice(0))await m.close();for(const d of dirs.splice(0))await rm(d,{recursive:true,force:true});vi.useRealTimers()})
function fixture(saved:BelleConnectionConfig|null=null,external=false,options:Partial<ConstructorParameters<typeof BelleConnectionManager>[0]>={}){
 const store={available:vi.fn(async()=>true),has:vi.fn(async()=>Boolean(saved)),put:vi.fn(async(_key:string)=>{}),get:vi.fn(async()=>key),remove:vi.fn(async()=>{})} satisfies RuntimeCredentialStore
 const metadata={load:vi.fn(async()=>saved),save:vi.fn(async(_value:BelleConnectionConfig|null)=>{})}
 const running={stop:vi.fn(async()=>{}),ready:vi.fn(async()=>true)}
 let exit:()=>void=()=>{}
 const runtime={probe:vi.fn(async()=>({clientVersion:'0.0.14',nodeVersion:'v22.23.0'})),start:vi.fn(async(_c,_k,_b,_s,onExit)=>{exit=onExit;return running})} satisfies TunnelRuntime
 const bridge={start:vi.fn(async(_s:AbortSignal)=>({port:12345,token:'local-session-token'})),stop:vi.fn(async()=>{})}
 const m=new BelleConnectionManager({store,metadata,runtime,bridge,external,retryDelay:()=>10,...options});managers.push(m)
 return {m,store,metadata,runtime,running,bridge,exit:()=>exit()}
}
describe('connection authority and storage',()=>{
 it('defaults unconfigured and off; snapshots/subscriptions never expose secrets',async()=>{const f=fixture();await f.m.initialize();expect(f.m.snapshot()).toMatchObject({state:'unconfigured',config:null,credentialStored:false});const seen:unknown[]=[];f.m.subscribe(v=>seen.push(v));const value={...ids,key};await f.m.configure(value);expect(value.key).toBe('');expect(f.store.put).toHaveBeenCalledWith(key);expect(f.metadata.save).toHaveBeenCalledWith(config);expect(JSON.stringify([f.m.snapshot(),seen,f.metadata.save.mock.calls])).not.toContain(key);expect(f.runtime.start).not.toHaveBeenCalled()})
 it('persisted off never reads a credential or launches; opted-in start does',async()=>{const f=fixture(config);await f.m.initialize();expect(f.store.get).not.toHaveBeenCalled();expect(f.runtime.start).not.toHaveBeenCalled();const g=fixture({...config,autoConnect:true});await g.m.initialize();await vi.waitFor(()=>expect(g.m.snapshot().state).toBe('ready'));expect(g.runtime.start).toHaveBeenCalledTimes(1)})
 it('disconnect turns persistent auto off, stops only owned child and releases bridge',async()=>{const f=fixture(config);await f.m.initialize();await f.m.setAutoConnect(true);await f.m.connect();expect(f.m.snapshot()).toMatchObject({state:'ready',muted:true});await f.m.disconnect();expect(f.running.stop).toHaveBeenCalledTimes(1);expect(f.bridge.stop).toHaveBeenCalled();expect(f.m.snapshot()).toMatchObject({state:'disconnected',config:{autoConnect:false}})})
 it('failed owned stop is an error, releases the bridge and retains its handle for an explicit retry',async()=>{const f=fixture(config);await f.m.initialize();await f.m.setAutoConnect(true);await f.m.connect();f.running.stop.mockRejectedValueOnce(Error('PRIVATE_STOP_ERROR'));await expect(f.m.disconnect()).rejects.toThrow('CONNECTION_FAILED');expect(f.m.snapshot()).toMatchObject({state:'error',error:'CONNECTION_FAILED',config:{autoConnect:false}});expect(f.bridge.stop).toHaveBeenCalled();await f.m.connect();expect(f.runtime.start).toHaveBeenCalledTimes(1);await f.m.disconnect();expect(f.running.stop).toHaveBeenCalledTimes(2);expect(f.m.snapshot()).toMatchObject({state:'disconnected',error:null})})
 it('start cleanup failure retains the not-ready handle and blocks automatic replacement until explicit cleanup',async()=>{vi.useFakeTimers();const f=fixture(config);await f.m.initialize();f.runtime.start.mockRejectedValue(new OwnedTunnelCleanupError(f.running));await f.m.connect();expect(f.m.snapshot()).toMatchObject({state:'error',error:'CONNECTION_FAILED',retry:0});await vi.advanceTimersByTimeAsync(30000);await f.m.connect();expect(f.runtime.start).toHaveBeenCalledTimes(1);expect(f.running.stop).not.toHaveBeenCalled();await f.m.disconnect();expect(f.running.stop).toHaveBeenCalledOnce();expect(f.m.snapshot().state).toBe('disconnected')})
 it('late not-ready ownership survives cancellation cleanup failure and does not launch a replacement',async()=>{const f=fixture(config);await f.m.initialize();let finish:(v:typeof f.running)=>void=()=>{};f.runtime.start.mockImplementation(()=>new Promise(resolve=>finish=resolve));f.running.stop.mockRejectedValue(Error('FAILED_STOP'));const connect=f.m.connect();await vi.waitFor(()=>expect(f.runtime.start).toHaveBeenCalledOnce());const disconnect=f.m.disconnect();const failed=expect(disconnect).rejects.toThrow('CONNECTION_FAILED');finish(f.running);await connect;await failed;expect(f.m.snapshot()).toMatchObject({state:'error',error:'CONNECTION_FAILED'});await f.m.connect();expect(f.runtime.start).toHaveBeenCalledTimes(1);f.running.stop.mockResolvedValue(undefined);await f.m.disconnect();expect(f.m.snapshot().state).toBe('disconnected')})
 it('disconnect always cleans owned runtime and bridge when metadata saving fails and reports SAVE_FAILED',async()=>{const f=fixture(config);await f.m.initialize();await f.m.setAutoConnect(true);await f.m.connect();f.metadata.save.mockRejectedValueOnce(Error('PRIVATE_DISK_ERROR'));await expect(f.m.disconnect()).rejects.toThrow('SAVE_FAILED');expect(f.running.stop).toHaveBeenCalledOnce();expect(f.bridge.stop).toHaveBeenCalled();expect(f.m.snapshot()).toMatchObject({state:'error',error:'SAVE_FAILED',muted:true});await f.m.disconnect();expect(f.m.snapshot()).toMatchObject({state:'disconnected',error:null,config:{autoConnect:false}})})
 it('repeat connect shares one process and close releases it without changing saved auto preference',async()=>{const f=fixture(config);await f.m.initialize();await f.m.setAutoConnect(true);await Promise.all([f.m.connect(),f.m.connect()]);expect(f.runtime.start).toHaveBeenCalledTimes(1);f.metadata.save.mockClear();await f.m.close();expect(f.running.stop).toHaveBeenCalledTimes(1);expect(f.metadata.save).not.toHaveBeenCalled();await expect(f.m.connect()).rejects.toThrow('SHUTTING_DOWN')})
 it('unavailable store fails closed without key/JSON fallback or launching',async()=>{const f=fixture(config);f.store.available.mockResolvedValue(false);await f.m.initialize();await expect(f.m.configure({...ids,key})).rejects.toThrow('STORE_UNAVAILABLE');await f.m.connect();expect(f.m.snapshot().error).toBe('STORE_UNAVAILABLE');expect(f.store.put).not.toHaveBeenCalled();expect(f.store.get).not.toHaveBeenCalled();expect(f.runtime.start).not.toHaveBeenCalled()})
 it.each(['STORE_LOCKED','STORE_DENIED','KEY_MISSING','CLIENT_MISSING','NODE_MISSING','LOCAL_NOT_READY'])('actionable %s does not retry',async code=>{const f=fixture(config);await f.m.initialize();f.store.get.mockRejectedValue(Error(code));await f.m.connect();expect(f.m.snapshot()).toMatchObject({state:'error',error:code,retry:0});expect(f.runtime.start).not.toHaveBeenCalled()})
 it('failed storage write restores prior metadata and never reports success',async()=>{const f=fixture(config);await f.m.initialize();f.store.put.mockRejectedValue(Error('STORE_DENIED'));await expect(f.m.configure({...ids,key})).rejects.toThrow('STORE_DENIED');expect(f.metadata.save.mock.calls.at(-1)?.[0]).toEqual(config);expect(f.m.snapshot().config).toEqual(config)})
 it('forget removes only app-owned credential+metadata and never remotely revokes a key',async()=>{const f=fixture(config);await f.m.initialize();await f.m.connect();await f.m.forget();expect(f.store.remove).toHaveBeenCalledTimes(1);expect(f.metadata.save).toHaveBeenLastCalledWith(null);expect(f.m.snapshot()).toMatchObject({state:'unconfigured',credentialStored:false,config:null})})
 it('external helper is not adopted/stopped/changed and cannot silently receive a stored key',async()=>{const f=fixture({...config,autoConnect:true},true);await f.m.initialize();expect(f.m.snapshot().state).toBe('external');await expect(f.m.connect()).rejects.toThrow('EXTERNAL_SESSION');await expect(f.m.configure({...ids,key})).rejects.toThrow('EXTERNAL_SESSION');expect(f.store.get).not.toHaveBeenCalled();expect(f.runtime.start).not.toHaveBeenCalled();expect(f.bridge.start).not.toHaveBeenCalled()})
 it('disconnect aborts an in-flight launch; a late ready child is stopped, not published',async()=>{const f=fixture(config);await f.m.initialize();let finish:(v:typeof f.running)=>void=()=>{};let signal:AbortSignal|undefined;f.runtime.start.mockImplementation(async(_c,_k,_b,s)=>{signal=s;return new Promise(resolve=>finish=resolve)});const connect=f.m.connect();await vi.waitFor(()=>expect(signal).toBeDefined());const stop=f.m.disconnect();expect(signal!.aborted).toBe(true);finish(f.running);await Promise.all([connect,stop]);expect(f.running.stop).toHaveBeenCalledTimes(1);expect(f.m.snapshot().state).toBe('disconnected')})
 it('retries are bounded at three and do not leak client errors',async()=>{vi.useFakeTimers();const f=fixture(config);await f.m.initialize();f.runtime.start.mockRejectedValue(Error('PRIVATE_CANARY '+key));await f.m.connect();for(let i=0;i<3;i++)await vi.advanceTimersByTimeAsync(20);expect(f.runtime.start).toHaveBeenCalledTimes(4);expect(f.m.snapshot()).toMatchObject({state:'error',error:'CONNECTION_FAILED',retry:3});expect(JSON.stringify(f.m.snapshot())).not.toContain(key)})
 it('disconnect cancels scheduled restart; stale exit cannot resurrect a connection',async()=>{vi.useFakeTimers();const f=fixture(config);await f.m.initialize();await f.m.connect();f.exit();await vi.advanceTimersByTimeAsync(0);await f.m.disconnect();await vi.advanceTimersByTimeAsync(100);expect(f.runtime.start).toHaveBeenCalledTimes(1);expect(f.m.snapshot().state).toBe('disconnected')})
 it('readiness loss/recovery reflects transport only without launching another client',async()=>{vi.useFakeTimers();const f=fixture(config);await f.m.initialize();await f.m.connect();f.running.ready.mockResolvedValue(false);await vi.advanceTimersByTimeAsync(5000);expect(f.m.snapshot().state).toBe('reconnecting');f.running.ready.mockResolvedValue(true);await vi.advanceTimersByTimeAsync(5000);expect(f.m.snapshot().state).toBe('ready');expect(f.runtime.start).toHaveBeenCalledTimes(1)})
})
describe('config and secure prerequisites',()=>{
 it.each([{},null,{...config,key:'private'},{...config,consentVersion:2},{...config,tunnelId:'https://evil.example'},{...config,organizationId:'org-example;execute'}])('restoration fails closed for malformed/extra fields %j',v=>expect(restoredConnectionConfig(v)).toBeNull())
 it('restores old missing autoconnect as off, validates bounded IDs and keys',()=>{expect(restoredConnectionConfig({...ids,consentVersion:1})?.autoConnect).toBe(false);expect(validRuntimeKey(key)).toBe(true);for(const v of ['bad','sk-'+ 'a'.repeat(1021),key+'\n'])expect(validRuntimeKey(v)).toBe(false);expect(connectionIds({...ids,tunnelId:ids.tunnelId+'x'})).toBeNull()})
 it('metadata contains only nonsecret allowlisted fields and atomic private mode',async()=>{const dir=await mkdtemp(join(tmpdir(),'belle-meta-test-'));dirs.push(dir);const m=new BelleConnectionMetadata(dir);await m.save(config);expect(await m.load()).toEqual(config);const path=join(dir,'belle-connection.json'),text=await readFile(path,'utf8');expect(text).not.toContain(key);if(process.platform!=='win32')expect((await stat(path)).mode&0o777).toBe(0o600);await expect(m.save({...config,key} as BelleConnectionConfig)).rejects.toThrow('INVALID_CONFIG');await m.save(null);expect(await m.load()).toBeNull()})
 it.each(['win32','linux'])('missing helper on %s never invokes a helper or writes plaintext',async platform=>{const store=new BelleCredentialStore('/does-not-exist',platform as NodeJS.Platform);expect(await store.available()).toBe(false);await expect(store.put(key)).rejects.toThrow('STORE_UNAVAILABLE');await expect(store.get()).rejects.toThrow('STORE_UNAVAILABLE')})
 it('sanitized child environment drops API keys, proxy/CA/log and launch overrides',()=>{const env=tunnelBaseEnv({HOME:'/home/example-user',CONTROL_PLANE_API_KEY:key,OPENAI_API_KEY:key,HTTP_PROXY:'evil',NODE_OPTIONS:'execute',ELECTRON_RUN_AS_NODE:'1',LOG_HTTP_RAW_UNSAFE:'1'});expect(env).toEqual({HOME:'/home/example-user'});expect(JSON.stringify(env)).not.toContain(key)})
 it.each([['0.0.14+sha','0.0.14'],['0.0.13',null],['1.2.3','1.2.3'],['PRIVATE_RAW',null]])('client version %s is checked', (v,result)=>expect(clientVersion(v)).toBe(result))
 it.each([['v22.13.0','v22.13.0'],['v22.12.9',null],['v24.18.1','v24.18.1'],['v21.1.0',null]])('Node version %s is checked',(v,result)=>expect(nodeVersion(v)).toBe(result))
 it('raw errors collapse to fixed public codes',()=>{expect(connectionError(Error(key))).toBe('CONNECTION_FAILED');expect(connectionError(Error('STORE_DENIED'))).toBe('STORE_DENIED')})
})

it('refresh rechecks owned runtime readiness without reading a key or starting a new connection',async()=>{const f=fixture(config);await f.m.initialize();await f.m.connect();f.store.get.mockClear();f.running.ready.mockResolvedValue(false);await f.m.refresh();expect(f.m.snapshot().state).toBe('reconnecting');f.running.ready.mockResolvedValue(true);await f.m.refresh();expect(f.m.snapshot().state).toBe('ready');expect(f.store.get).not.toHaveBeenCalled();expect(f.runtime.start).toHaveBeenCalledOnce()})

it.each(['STORE_LOCKED','STORE_DENIED'])('refresh publishes %s and invalidates cached credentials without reading or changing them',async code=>{const f=fixture(config);await f.m.initialize();await f.m.connect();f.store.get.mockClear();const seen:unknown[]=[];f.m.subscribe(value=>seen.push(value));f.store.has.mockRejectedValueOnce(Error(code));const failed=await f.m.refresh();expect(failed).toMatchObject({credentialStored:false,secureStore:'unavailable',error:code,config});expect(seen.at(-1)).toEqual(failed);expect(f.store.get).not.toHaveBeenCalled();expect(f.store.put).not.toHaveBeenCalled();expect(f.store.remove).not.toHaveBeenCalled();expect(f.metadata.save).not.toHaveBeenCalled();expect(f.running.stop).not.toHaveBeenCalled();expect(f.runtime.start).toHaveBeenCalledOnce();const checked=await f.m.refresh();expect(checked).toMatchObject({state:'ready',credentialStored:true,secureStore:'macos-keychain',error:null});expect(f.store.get).not.toHaveBeenCalled()})

it('diagnostic run preserves saved auto preference but waits for one explicit connect and never retries',async()=>{
 vi.useFakeTimers();const events:unknown[]=[];const f=fixture({...config,autoConnect:true},false,{manualConnectOnly:true,diagnostic:e=>events.push(e)})
 await f.m.initialize();expect(f.store.get).not.toHaveBeenCalled();expect(f.runtime.start).not.toHaveBeenCalled();expect(f.metadata.save).not.toHaveBeenCalled()
 f.runtime.start.mockRejectedValue(Error('PRIVATE_CANARY '+key));await f.m.connect();await vi.advanceTimersByTimeAsync(30000)
 expect(f.runtime.start).toHaveBeenCalledOnce();expect(f.m.snapshot()).toMatchObject({state:'error',retry:0,config:{autoConnect:true}})
 expect(events).toEqual(expect.arrayContaining([expect.objectContaining({source:1,phase:5,code:12})]));expect(JSON.stringify(events)).not.toContain(key)
 await f.m.close();expect(f.metadata.save).not.toHaveBeenCalled()
})
it('diagnostic callback failure never changes a successful connection',async()=>{const f=fixture(config,false,{diagnostic:()=>{throw Error('PRIVATE')}});await f.m.initialize();await f.m.connect();expect(f.m.snapshot().state).toBe('ready')})
