import {beforeEach,afterEach,expect,it,vi} from 'vitest'
import {BelleConnectionIpcController} from '../electron/main/dot/BelleConnectionIpcController'
import {BELLE_CONNECTION_IPC as I} from '../electron/shared/belle-connection'
const mocks=vi.hoisted(()=>({handlers:new Map<string,Function>(),dialog:vi.fn(),open:vi.fn()}))
vi.mock('electron',()=>({ipcMain:{handle:(c:string,h:Function)=>mocks.handlers.set(c,h),removeHandler:(c:string)=>mocks.handlers.delete(c)},dialog:{showMessageBox:mocks.dialog},shell:{openExternal:mocks.open},BrowserWindow:class{}}))
const controllers:BelleConnectionIpcController[]=[]
beforeEach(()=>{mocks.handlers.clear();mocks.open.mockReset();mocks.open.mockResolvedValue(undefined);mocks.dialog.mockReset();mocks.dialog.mockResolvedValue({response:0})})
afterEach(()=>controllers.splice(0).forEach(c=>c.dispose()))
function fixture(){let owner='owner';const frame={url:'pet://app/settings.html'},contents={id:8,mainFrame:frame},window={window:{webContents:contents,isDestroyed:()=>false},currentOwner:()=>owner,send:vi.fn()};const config={tunnelId:'tunnel_'+'a'.repeat(32),organizationId:'org-example123',autoConnect:false,consentVersion:1};const manager={refresh:vi.fn(async()=>({})),snapshot:vi.fn(()=>({state:'disconnected',config})),configure:vi.fn(async()=>({})),connect:vi.fn(async()=>({})),disconnect:vi.fn(async()=>({})),setAutoConnect:vi.fn(async()=>({})),forget:vi.fn(async()=>({})),subscribe:vi.fn(()=>vi.fn())};const c=new BelleConnectionIpcController(manager as any,window as any);controllers.push(c);c.register();const event={sender:contents,senderFrame:frame};return {manager,frame,contents,event,window,config,owner:(v:string)=>owner=v,call:(channel:string,args:unknown[]=[],e:unknown=event)=>mocks.handlers.get(channel)!(e,...args)}}
it('all connection IPC rejects other windows, changed URLs and same-URL subframes',async()=>{const f=fixture();for(const c of mocks.handlers.keys())for(const e of [{sender:f.contents,senderFrame:{url:f.frame.url}},{sender:{id:9},senderFrame:f.frame},{sender:f.contents,senderFrame:{url:'pet://app/pet.html'}}])expect(await f.call(c,[],e)).toMatchObject({ok:false,code:'UNTRUSTED_SENDER'});expect(mocks.dialog).not.toHaveBeenCalled();expect(f.manager.configure).not.toHaveBeenCalled()})
it('cancel-by-default configure does not store or connect and clears the IPC payload',async()=>{const f=fixture(),value={...f.config,key:'sk-'+Array.from({length:24},()=> 'q').join('')};delete (value as any).autoConnect;delete (value as any).consentVersion;expect(await f.call(I.configure,[value])).toMatchObject({ok:true});expect(mocks.dialog).toHaveBeenCalledWith(f.window.window,expect.objectContaining({defaultId:0,cancelId:0}));expect(f.manager.configure).not.toHaveBeenCalled();expect(f.manager.connect).not.toHaveBeenCalled();expect(value.key).toBe('')})
it('affirmative exact-target dialog precedes storage; dialog contains no key',async()=>{const f=fixture(),key='sk-'+Array.from({length:24},()=> 'q').join(''),value={tunnelId:f.config.tunnelId,organizationId:f.config.organizationId,key};mocks.dialog.mockResolvedValue({response:1});await f.call(I.configure,[value]);expect(f.manager.configure).toHaveBeenCalledTimes(1);const options=mocks.dialog.mock.calls[0][1];expect(options.title).toBe('Dots 연결 확인');expect(options.detail).toContain(f.config.tunnelId);expect(options.detail).toContain(f.config.organizationId);expect(options.detail).not.toContain(key);expect(f.manager.connect).not.toHaveBeenCalled();expect(value.key).toBe('')})
it('closing/reloading settings during the confirmation invalidates consent',async()=>{const f=fixture();mocks.dialog.mockImplementation(async()=>{f.owner('new-owner');return {response:1}});await f.call(I.connect);expect(f.manager.connect).not.toHaveBeenCalled()})
it('auto-connect requires separate specific consent, not just an unchecked checkbox',async()=>{const f=fixture();await f.call(I.auto,[true]);expect(f.manager.setAutoConnect).not.toHaveBeenCalled();mocks.dialog.mockResolvedValue({response:1});await f.call(I.auto,[true]);expect(f.manager.setAutoConnect).toHaveBeenCalledWith(true);expect(mocks.dialog.mock.calls.at(-1)![1].detail).toContain('OS 로그인 서비스');await f.call(I.auto,[false]);expect(f.manager.setAutoConnect).toHaveBeenCalledWith(false)})
it('rejects credential-read/migration/arbitrary command paths and unknown configure keys',async()=>{const f=fixture();expect([...mocks.handlers.keys()]).toHaveLength(8);expect([...mocks.handlers.keys()].join(',')).not.toMatch(/read-key|environment|terminal|execute/);expect(await f.call(I.configure,[{...f.config,key:'key',command:'execute'}])).toMatchObject({ok:false});expect(await f.call(I.connect,['arbitrary'])).toMatchObject({ok:false});expect(f.manager.configure).not.toHaveBeenCalled()})
it('disconnect is immediate and forget is confirmed without remote revocation',async()=>{const f=fixture();await f.call(I.disconnect);expect(f.manager.disconnect).toHaveBeenCalledTimes(1);expect(mocks.dialog).not.toHaveBeenCalled();await f.call(I.forget);expect(f.manager.forget).not.toHaveBeenCalled();mocks.dialog.mockResolvedValue({response:1});await f.call(I.forget);expect(f.manager.forget).toHaveBeenCalledTimes(1);expect(mocks.dialog.mock.calls.at(-1)![1].detail).toContain('Platform의 키나 터널 권한은 취소하지')})
it('public errors never echo the key or raw client stderr',async()=>{const f=fixture();mocks.dialog.mockResolvedValue({response:1});f.manager.connect.mockRejectedValue(Error('PRIVATE_KEY_CANARY'));expect(await f.call(I.connect)).toEqual({ok:false,code:'CONNECTION_FAILED'})})

it('official guides accept only fixed names, never arbitrary URL input or credentials',async()=>{const f=fixture();for(const value of ['https://evil.example','https://chatgpt.com/plugins?key=private','__proto__','constructor',{url:'https://chatgpt.com/plugins'},null])expect(await f.call(I.guide,[value])).toMatchObject({ok:false});expect(mocks.open).not.toHaveBeenCalled();expect(await f.call(I.guide,['plugins'])).toMatchObject({ok:true});expect(mocks.open).toHaveBeenCalledWith('https://chatgpt.com/plugins');expect(mocks.dialog).not.toHaveBeenCalled();expect(f.manager.connect).not.toHaveBeenCalled()})
