import {beforeAll,afterAll,afterEach,expect,it,vi} from 'vitest'
import {mkdtemp,writeFile,readFile,rm,rename,mkdir,symlink} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {build} from 'esbuild'
import {ReferenceProfileStore,workerReferenceConverter} from '../electron/main/character-voice/ReferenceProfileStore'
import {referenceWav} from './helpers/reference-wav'
let worker:string,buildRoot:string;const roots:string[]=[]
beforeAll(async()=>{buildRoot=await mkdtemp(join(tmpdir(),'reference-worker-test-'));worker=join(buildRoot,'reference-worker.cjs');await build({entryPoints:['electron/utility/reference-import-worker.ts'],bundle:true,platform:'node',format:'cjs',outfile:worker})})
afterAll(async()=>{await rm(buildRoot,{recursive:true,force:true})})
afterEach(async()=>{vi.restoreAllMocks();for(const r of roots.splice(0))await rm(r,{recursive:true,force:true})})
async function fixture(limits?:{maxProfiles:number;maxStoreBytes:number}){const root=await mkdtemp(join(tmpdir(),'reference-store-'));roots.push(root);const path=join(root,'개인 원본.wav');await writeFile(path,referenceWav());const store=new ReferenceProfileStore(join(root,'store'),workerReferenceConverter(worker),limits);await store.initialize();return{root,path,store,signal:new AbortController().signal}}
it('imports an owned canonical snapshot; original removal and restart preserve it',async()=>{const f=await fixture(),original=await readFile(f.path),p=await f.store.import(f.path,'나의 음성',f.signal),key=p.id+'@'+p.version;expect(p).not.toHaveProperty('adapterSha256');expect(JSON.stringify(p)).not.toContain(f.path);expect(await readFile(f.path)).toEqual(original);await rm(f.path);await f.store.initialize();expect(f.store.list()).toEqual([p]);const c=await f.store.resolve(key);expect(await readFile(c.path)).toEqual(original);expect(c.sha256).toBe(p.referenceSha256)})
it('renames without changing conditioning identity or reference metadata',async()=>{const f=await fixture(),p=await f.store.import(f.path,'First',f.signal),key=p.id+'@'+p.version,before=await f.store.resolve(key);await f.store.rename(key,'Second');expect(await f.store.resolve(key)).toEqual(before);expect(f.store.list()[0]).toEqual({...p,name:'Second'});await f.store.initialize();expect(f.store.list()[0].name).toBe('Second')})
it('isolates one corrupt profile and never substitutes another reference',async()=>{const f=await fixture(),a=await f.store.import(f.path,'A',f.signal),b=await f.store.import(f.path,'B',f.signal),ak=a.id+'@'+a.version,bk=b.id+'@'+b.version;const c=await f.store.resolve(ak);await writeFile(c.path,Buffer.from('broken'));await f.store.initialize();expect(f.store.list().find(p=>p.id===a.id)?.error).toBe('VOICE_REFERENCE_UNAVAILABLE');await expect(f.store.resolve(ak)).rejects.toThrow('CHANGED');await expect(f.store.resolve(bk)).resolves.toHaveProperty('sha256',b.referenceSha256)})
it('changed samples with unchanged size invalidate a warm verification lease',async()=>{const f=await fixture(),p=await f.store.import(f.path,'A',f.signal),key=p.id+'@'+p.version,c=await f.store.resolve(key),bytes=await readFile(c.path);bytes.writeInt16LE(1000,44);await writeFile(c.path,bytes);await expect(f.store.resolve(key)).rejects.toThrow('CHANGED')})
it('rejects symlink/junction sources and leaves the destination unregistered',async()=>{const f=await fixture(),link=join(f.root,'linked');await symlink(f.root,link,process.platform==='win32'?'junction':'dir');await expect(f.store.import(join(link,'개인 원본.wav'),'Linked',f.signal)).rejects.toThrow('FILE');expect(f.store.list()).toEqual([])})
it('cancelled decode cannot publish, and the next import recovers',async()=>{const f=await fixture(),convert=workerReferenceConverter(worker),c=new AbortController();let entered!:()=>void;const started=new Promise<void>(r=>entered=r);const store=new ReferenceProfileStore(join(f.root,'cancel'),async(...args)=>{entered();await new Promise<void>(r=>args[2].addEventListener('abort',()=>r(),{once:true}));return convert(...args)});await store.initialize();const task=store.import(f.path,'Cancelled',c.signal);await started;c.abort();await expect(task).rejects.toThrow('CANCELLED');expect(store.list()).toEqual([]);await expect(f.store.import(f.path,'Recovered',f.signal)).resolves.toHaveProperty('name','Recovered')})
it('rejects stale ownership after conversion and leaves no registered profile',async()=>{const f=await fixture(),convert=workerReferenceConverter(worker);let current=true;const store=new ReferenceProfileStore(join(f.root,'stale'),async(...args)=>{const result=await convert(...args);current=false;return result});await store.initialize();await expect(store.import(f.path,'Stale',f.signal,()=>current)).rejects.toThrow('CANCELLED');await store.initialize();expect(store.list()).toEqual([])})
it('registry commit failure leaves old profiles intact and new data unregistered',async()=>{const f=await fixture(),a=await f.store.import(f.path,'A',f.signal),before=await readFile(join(f.store.root,'registry.json'));vi.spyOn(f.store as any,'commit').mockRejectedValueOnce(Error('synthetic failure'));await expect(f.store.import(f.path,'B',f.signal)).rejects.toThrow('synthetic failure');expect(await readFile(join(f.store.root,'registry.json'))).toEqual(before);await f.store.initialize();expect(f.store.list()).toEqual([a])})
it('enforces count/storage quotas and frees quota after removal',async()=>{const f=await fixture({maxProfiles:1,maxStoreBytes:128*1024*1024}),a=await f.store.import(f.path,'A',f.signal);await expect(f.store.import(f.path,'B',f.signal)).rejects.toThrow('COUNT');await f.store.remove(a.id+'@'+a.version);await expect(f.store.import(f.path,'B',f.signal)).resolves.toHaveProperty('name','B');const tiny=new ReferenceProfileStore(join(f.root,'small'),workerReferenceConverter(worker),{maxProfiles:32,maxStoreBytes:64000});await tiny.initialize();await expect(tiny.import(f.path,'Too big',f.signal)).rejects.toThrow('STORAGE_LIMIT')})
it('corrupt registry is preserved, blocks writes, and never scans orphan folders as registered',async()=>{const f=await fixture();const a=await f.store.import(f.path,'A',f.signal);const registry=join(f.store.root,'registry.json');await writeFile(registry,'invalid');await f.store.initialize();expect(f.store.list()).toEqual([]);await expect(f.store.import(f.path,'B',f.signal)).rejects.toThrow('STORAGE');await expect(f.store.remove(a.id+'@'+a.version)).rejects.toThrow('STORAGE');expect(await readFile(registry,'utf8')).toBe('invalid')})
it('startup cleans abandoned staging but preserves unrelated files',async()=>{const f=await fixture(),owned=join(f.store.root,'staging','tx-11111111-1111-4111-8111-111111111111'),other=join(f.store.root,'staging','unrelated');await mkdir(owned);await writeFile(join(owned,'partial'),'partial');await writeFile(other,'keep');await f.store.initialize();await expect(readFile(join(owned,'partial'))).rejects.toThrow();expect(await readFile(other,'utf8')).toBe('keep')})
it('rejects manifests that attempt to add external command/path configuration',async()=>{const f=await fixture(),p=await f.store.import(f.path,'A',f.signal),key=p.id+'@'+p.version,c=await f.store.resolve(key),path=join(c.path,'..','profile.json'),m=JSON.parse(await readFile(path,'utf8'));m.python='/arbitrary';await writeFile(path,JSON.stringify(m));await expect(f.store.resolve(key)).rejects.toThrow('CHANGED')})
