import {afterEach,expect,it,vi} from 'vitest'
import {mkdtemp,rm,writeFile,readFile} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {CharacterVoiceService} from '../electron/main/character-voice/CharacterVoiceService'
import {VoiceReplayCache,VOICE_REPLAY_LIMITS} from '../electron/main/character-voice/VoiceReplayCache'
import {validVoiceSeed,validSeedSettings} from '../electron/shared/voice-seed'
import {randomUUID} from 'node:crypto'
const clean:Array<()=>Promise<unknown>>=[]
afterEach(async()=>{for(const fn of clean.splice(0))await fn()})
function wav(samples=4800){const b=Buffer.alloc(44+samples*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(48000,24);b.writeUInt32LE(96000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(samples*2,40);b[50]=11;return b}
async function fixture(){
 const root=await mkdtemp(join(tmpdir(),'voice-seeds-'));let identity='assets',capture=true
 const message:any={id:'reply',role:'assistant',status:'complete',text:'아침에는 창문을 열고 차를 준비했어. 아, 그런데 비가 내리기 시작했네. 그럼 안에서 책을 읽으며 조금 쉬자.',binding:{characterId:'c',revision:'1',conversationId:'chat',requestId:'r',epoch:1,modelId:'E4B'}}
 const chat:any={epoch:1,model:'E4B',character:{id:'c',revision:'1'},conversation:{id:'chat',messages:[message]}}
 const base:any={native:false,profile:{id:'voxcpm2_default',version:'1',name:'Default',kind:'base-default',fingerprint:'base',adapterSha256:'none'},executable:'/managed/python',path:'/managed/model',snapshot:()=>({supported:true,installed:true,phase:'idle'}),initialize:async()=>{},identity:async()=>identity,ready:vi.fn(async()=>'/managed/model'),cancelVerification:async()=>{},cancel:async()=>{}}
 let nextSeed=100;const random=vi.fn(()=>++nextSeed),events:any[]=[],played:Buffer[]=[]
 const runtime:any={running:false,busy:false,sessionId:'worker-session',audit:{seedContract:1},get ready(){return this.running},retireSpeech:vi.fn(),start:vi.fn(async()=>{runtime.running=true}),stop:vi.fn(async()=>{runtime.running=false}),cancelSpeech:vi.fn(async()=>({keptWarm:true,elapsedMs:1})),stream:vi.fn(async(_text,binding,index,accept)=>{await accept({audioId:randomUUID(),bytes:wav(),durationMs:100,generationMs:1,rtf:.01,synthesisId:randomUUID(),chunkIndex:0,sampleOffset:0,sampleCount:4800,firstChunkReadyMs:1});return {totalSamples:4800,totalChunks:1,effectiveSeed:binding.effectiveSeed}})}
 const service=new CharacterVoiceService(root,'/worker',()=>chat,()=>{},e=>{events.push(e);if(e.type==='audio'&&capture)queueMicrotask(()=>{try{played.push(Buffer.from(service.audio(e.audioId,e.epoch)));service.played(e.audioId,e.epoch)}catch{}})},config=>{runtime.config=config;return runtime},()=>{},base,undefined,undefined,random)
 clean.push(async()=>{await service.close();await rm(root,{recursive:true,force:true})});await service.initialize();await service.enabled(true);service.setOutputReady(true);await service.prepare()
 const read=(mode='read')=>(service as any).read(message,false,false,mode)
 return{service,message,chat,runtime,random,base,events,played,read,root,identity:(v:string)=>{identity=v},capture:(v:boolean)=>{capture=v}}
}
it.each([1,42,2147483647])('accepts interoperable integer seed %s',value=>expect(validVoiceSeed(value)).toBe(true))
it.each([0,-1,2147483648,1.5,NaN,Infinity,true,false,null,undefined,'42'])('rejects non-contract seed %s',value=>{expect(validVoiceSeed(value)).toBe(false);expect(validSeedSettings({mode:'fixed',fixedSeed:value})).toBe(false)})
it('one random draw per reply, all groups share seed; warmup never draws',async()=>{const f=await fixture();expect(f.random).not.toHaveBeenCalled();await f.read();expect(f.random).toHaveBeenCalledTimes(1);expect(f.runtime.stream.mock.calls.length).toBeGreaterThan(1);expect(new Set(f.runtime.stream.mock.calls.map((a:any)=>a[1].effectiveSeed))).toEqual(new Set([101]));expect(new Set(f.runtime.stream.mock.calls.map((a:any)=>a[1].generationId)).size).toBe(1);expect(f.base.ready).toHaveBeenCalledTimes(1)})
it('fixed/reroll/reproduce retain global mode and warm worker',async()=>{const f=await fixture();await f.service.seedSettings({mode:'fixed',fixedSeed:42});await f.read();f.random.mockReturnValueOnce(42).mockReturnValueOnce(17);await f.read('reroll');expect(f.service.snapshot().lastGeneration?.effectiveSeed).toBe(17);expect(f.service.snapshot().seedSettings).toEqual({mode:'fixed',fixedSeed:42});await f.read('reproduce');expect(f.service.snapshot().lastGeneration?.effectiveSeed).toBe(17);expect(f.runtime.start).toHaveBeenCalledTimes(1);expect(f.base.ready).toHaveBeenCalledTimes(1)})
it('replay is bit-identical, new capabilities/owner, no synthesis or credit',async()=>{const f=await fixture();await f.read();const count=f.runtime.stream.mock.calls.length,old=f.events.filter(e=>e.type==='audio'),pcm=Buffer.concat(f.played);f.played.length=0;await f.read('replay');expect(f.runtime.stream).toHaveBeenCalledTimes(count);expect(Buffer.concat(f.played)).toEqual(pcm);const fresh=f.events.filter(e=>e.type==='audio').slice(old.length);expect(fresh.every(e=>!('runtimeSessionId'in e.binding)&&e.binding.playbackId&&e.binding.sourceGenerationId)).toBe(true);expect(fresh.every(e=>!old.some(o=>o.audioId===e.audioId||o.epoch===e.epoch))).toBe(true);for(const e of old)expect(()=>f.service.audio(e.audioId,e.epoch)).toThrow('EXPIRED')})
it('settings changed during generation apply only to next reply and save failure rolls back',async()=>{const f=await fixture();await f.service.seedSettings({mode:'fixed',fixedSeed:17});const original=f.runtime.stream.getMockImplementation();f.runtime.stream.mockImplementationOnce(async(...args:any[])=>{await f.service.seedSettings({mode:'fixed',fixedSeed:777});return original!(...args)});await f.read();expect(f.runtime.stream.mock.calls.every((a:any)=>a[1].effectiveSeed===17)).toBe(true);await f.read();expect(f.service.snapshot().lastGeneration?.effectiveSeed).toBe(777);vi.spyOn(f.service as any,'save').mockRejectedValueOnce(Error('VOICE_STORAGE'));await f.service.seedSettings({mode:'fixed',fixedSeed:123});expect(f.service.snapshot().seedSettings?.fixedSeed).toBe(777)})
it('voice stop keeps completed result; failed reroll cannot replace it; hide clears',async()=>{const f=await fixture();await f.read();const old=f.service.snapshot().results!.reply;f.runtime.stream.mockRejectedValueOnce(Error('CUDA_OOM'));await f.read('reroll');expect(f.service.snapshot().results!.reply).toEqual(old);await f.service.stop(true,false);expect(f.service.snapshot().results!.reply.cached).toBe(true);await f.read('replay');f.service.setOutputReady(false);expect(f.service.snapshot().results).toEqual({})})
it('partial cancellation and late completion cannot publish or overwrite a newer result',async()=>{const f=await fixture();await f.read();const original=f.service.snapshot().results!.reply;let release!:()=>void;f.runtime.stream.mockImplementationOnce(()=>new Promise<void>(r=>release=r));const pending=f.read('reroll');await vi.waitFor(()=>expect(release).toBeTypeOf('function'));await f.service.stop(true,false);expect(f.service.snapshot().results!.reply).toEqual(original);await f.read('reroll');const next=f.service.snapshot().results!.reply;release();await pending;expect(f.service.snapshot().results!.reply).toEqual(next)})
it('same-message text/asset change rejects cached playback without random synthesis',async()=>{const f=await fixture();await f.read();const calls=f.runtime.stream.mock.calls.length;f.identity('changed');await f.read('replay');expect(f.service.snapshot().error).toBe('VOICE_REPLAY_MISSING');expect(f.runtime.stream).toHaveBeenCalledTimes(calls);f.identity('assets');f.message.text+=' 다른 내용';await f.read('reproduce');expect(f.service.snapshot().error).toBe('VOICE_REPRODUCE_CHANGED');expect(f.runtime.stream).toHaveBeenCalledTimes(calls)})
it('context switch deletes completed audio and lightweight metadata',async()=>{const f=await fixture();await f.read();f.chat.conversation.id='other';f.service.onChatChanged();expect(f.service.snapshot().results).toEqual({})})
it('old settings migrate while invalid seed fields preserve voice settings and require repair',async()=>{const f=await fixture();await f.service.close();const path=join(f.root,'settings.json'),saved=JSON.parse(await readFile(path,'utf8'));saved.seedSettings={mode:'fixed',fixedSeed:true};saved.volume=.35;await writeFile(path,JSON.stringify(saved));const s=new CharacterVoiceService(f.root,'/worker',()=>f.chat,()=>{},()=>{});clean.push(()=>s.close());await s.initialize();expect(s.snapshot()).toMatchObject({enabled:true,volume:.35,seedError:true});await s.seedSettings({mode:'fixed',fixedSeed:42});expect(s.snapshot()).toMatchObject({seedError:false,seedSettings:{mode:'fixed',fixedSeed:42}})})
function plan(id:string){return {generationId:randomUUID(),messageId:id,effectiveSeed:42,seedPolicy:'fixed' as const,voiceFingerprint:'v',speechPlanFingerprint:'p'}}
it('LRU, PCM ownership, metadata cap and partial discard are bounded',()=>{const c=new VoiceReplayCache(),b=wav();for(let i=0;i<10;i++){const a=c.begin('x',plan(String(i)),{});c.append(a,b,0);c.publish(a)}expect(Object.values(c.infos()).filter(v=>v.cached)).toHaveLength(8);expect(c.get('0','x')).toBeUndefined();const copy=c.get('9','x')!.parts[0].bytes;b[50]=12;expect(copy[50]).toBe(11);for(let i=10;i<145;i++){const a=c.begin('x',plan(String(i)),{});c.discard(a);c.publish(a)}expect(Object.keys(c.infos())).toHaveLength(128);expect(c.retainedBytes).toBeLessThanOrEqual(VOICE_REPLAY_LIMITS.bytes);c.clear();expect(c.retainedBytes).toBe(0)})
it('result and shared retention budgets abandon only caching; last successful candidate stays intact',()=>{const c=new VoiceReplayCache(),b=wav(2_000_000);for(let i=0;i<4;i++){const a=c.begin('x',plan(String(i)),{});for(let n=0;n<4;n++)c.append(a,b,n);c.publish(a)}const a=c.begin('x',plan('0'),{});c.append(a,b,0);expect(a.retained).toBe(false);expect(c.get('0','x')).toBeDefined();c.publish(a);expect(c.infos()['0']).toMatchObject({cached:false,latestUnstored:true});expect(c.retainedBytes).toBeLessThanOrEqual(VOICE_REPLAY_LIMITS.bytes);c.clear();const huge=c.begin('x',plan('huge'),{});for(let i=0;i<5;i++)c.append(huge,b,i);expect(huge.retained).toBe(false);expect(c.retainedBytes).toBe(0)})
it('cached playback is bounded and stale PCM is revoked by live replacement',async()=>{const f=await fixture();await f.read();const generation=f.service.snapshot().lastGeneration!.generationId;f.capture(false);const pending=f.read('replay');await vi.waitFor(()=>expect(f.events.filter(e=>e.type==='audio'&&'playbackId'in e.binding).length).toBeGreaterThan(0));const old=f.events.filter(e=>e.type==='audio'&&'playbackId'in e.binding);expect(old.length).toBeLessThanOrEqual(3);await f.service.stop(true,false);for(const e of old)expect(()=>f.service.audio(e.audioId,e.epoch)).toThrow('EXPIRED');await pending;expect(f.service.snapshot().lastGeneration?.generationId).toBe(generation);f.capture(true);await f.read('reroll');expect(f.service.snapshot().lastGeneration?.generationId).not.toBe(generation)})
it('stale settings context is refused and fixed state survives restart',async()=>{const f=await fixture();await f.service.seedSettings({mode:'fixed',fixedSeed:2026});await f.service.seedSettings({mode:'fixed',fixedSeed:17},()=>false);expect(f.service.snapshot().seedSettings?.fixedSeed).toBe(2026);const saved=JSON.parse(await readFile(join(f.root,'settings.json'),'utf8'));expect(saved.seedSettings).toEqual({mode:'fixed',fixedSeed:2026});expect(saved.enabled).toBe(true);expect(saved.volume).toBe(.8)})
